name: Build and Upload Plugin

on:
  push:
    tags:
      - '2.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build plugin
        run: ./gradlew assemble -Dopensearch.version=2.19.2

      - name: Upload plugin to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
